# Generated by Django 4.0.5 on 2022-06-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_employee_departmentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DepartmentName',
            field=models.CharField(max_length=40),
        ),
    ]
